
import "./globals.css";

import Topo from "@/app/componentes/Topo"
import Rodape from "@/app/componentes/Rodape"


export const metadata = {
  title: "Gelateria - Sorveteria Artesanal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
    
      <body>

      <Topo/>


    
      {children}



      <Rodape/>

      </body>
    
    </html>
  );
}
